# Generated by Django 5.0.6 on 2024-05-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('ingredients', models.TextField()),
                ('indications', models.TextField()),
                ('dosage', models.TextField()),
                ('precautions', models.TextField()),
            ],
        ),
    ]
