# Generated by Django 5.0.6 on 2024-05-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugmodel',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='drugmodel',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='drugmodel',
            name='indications',
        ),
        migrations.RemoveField(
            model_name='drugmodel',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='drugmodel',
            name='precautions',
        ),
        migrations.AddField(
            model_name='drugmodel',
            name='contraindications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
